### ISSUE TITLE
(2) MVP assessment of DAMS content support

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#520]
### Descriptive summary
DAMS team has determined that we need to do an MVP assessment of our back-end needs for the DAMS including estimating the size (number of objects and file sizes) of our average ingests and how much new content we might anticipate putting up in production annually.  We want to be sure that any ask we make of ITS will accommodate future growth.

### Background
The need for increased disk space came up as an issue in connection with the Aerial Photos ingest.

### Acceptance criteria
**Done means:**
- [x] Determine average size of ingests (image, audio, etc.)
- [x] Estimate volume of material (size of the data) represented on the DAMS project and the Digital Projects GitHub boards
- [x] Estimate the volume of the material within SC&A's A/V digitization project
- [x] Identify and describe other back-end needs in support of collections

### Related work
Consider revisiting: https://docs.google.com/document/d/13UYjqzNS0BD-lZuCYGQj30N58kNWyzpOjhjTR8UXCo0/edit#heading=h.qgs08fx90qbn)

**Comment by rmjaffe** [comment]
@chesleyperry Wanted to follow up on this one -- was hoping to have all the MVP pieces completed by the end of the current dev cycle, i.e. mid- to end of March.  Do you have capacity for this between now and then?

**Comment by chesleyperry** [comment]
Yes.  That shouldn't be a problem.  I've started updating the cards on the Digital Projects Workflow board and can finish up the other estimates in the next two weeks.

**Comment by rmjaffe** [comment]
Thank you!  I'll bring this into the current sprint.  How many points worth of effort should I put on it?

**Comment by chesleyperry** [comment]
I think 2 points should do it

**Comment by chesleyperry** [comment]
Done - estimates are [here in a Google Doc](https://docs.google.com/spreadsheets/d/1bGJisi00oTQN0wdFSbMItWf_oR8VxZ2iUXOF640fCQg/edit?usp=sharing).

Questions: 

1. How and where does the DAMS team want to document the average file sizes for different analog format types?
2. AV format filesizes are calculated using the access files (mp3 and mp4) rather than the preservation files because the preservation files are much much bigger.  Depending on the ingest process for AV files, this might change.
