### ISSUE TITLE
A/V player breaks when accessing page via back button

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#57]
The player loads and plays as expected on initial view of a page. But if I click into one of the component lectures then use the back button to re-enter the course page, the player no longer works.

**Comment by NedHenry** [comment]
This seems to have to do with browser caching of the media player. I think the browser's "back-forward cache" keeps the player loaded when you navigate away from the page, but then the page partially reloads and breaks when you navigate back. So far I can't figure out why it is partially reloading or how to fix it, but I am making progress in understanding the problem.

**Comment by NedHenry** [comment]
Another relevant observation: if you navigate to a different domain and then press "back", the player loads correctly. It is only a problem when navigating back and forth within our domain.

**Comment by NedHenry** [comment]
It looks like the mediaelement.js autoloading feature is trying to load the already-loaded player, causing a problem. I hope to fix the problem by loading mediaelement.js manually.

**Comment by NedHenry** [comment]
This was fixed in May by changing the way we load mediaelement.js (as mentioned above). I apologize for never coming back and closing this issue. The issue was fixed in commits:
4f131c441b40a69c6a7ab227aa5b4c4753bb6022
fd7a14662a45696821de95dfa03f52d93726723c
714f09392695b62bf8236f9c102e6a06891bc42e
I have not seen the issue again since then, loading the pages in Firefox, Chrome and Safari on OSX and Chrome on Android. Please reopen this issue with a specific error report if this problem recurs.
