### ISSUE TITLE
RMB Haight-Ashbury: metadata elements not displaying

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#61]
The Rights Holder and Access Rights elements are not displaying in the metadata.

**Comment by rmjaffe** [comment]
Physical Format is also not displaying.

**Comment by NedHenry** [comment]
Each of these was a separate issue.
Rights Holder was omitted by mistake (or by someone's earlier decision), and I am adding it.
Access Rights was used to create the item's access policy in Hyrax, rather than storing it as a standard piece of metadata. As one point we thought this way would be better for lack of redundancy, but it continues to cause confusion when you review the metadata in the system. Despite the redundancy, I will populate the standard metadata elements for AccessRights on each item as soon as we get Fedora back online. 
I believe that the Physical Formal metadata was not included in the metadata spreadsheets at the time I ingested the items. I believe this was a requested metadata update that I never got around to applying, because the site has been under constant development and it has never been the highest priority. I can add that metadata when I make the other requested metadata changes.

**Comment by NedHenry** [comment]
Each of these issues has been fixed by now. An example of a record with each of these metadata elements on display is: http://digitalcollections.library.ucsc.edu/concern/works/8g84mm305
