### ISSUE TITLE
Large Image not displaying

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#62]
Looks like alt tag for the large image in the Item Record is displaying, but no image. Thumbnail is displaying in Item Record as expected.

**Comment by NedHenry** [comment]
Thanks for reporting this! I'm checking it out now.

**Comment by NedHenry** [comment]
This is being caused by the SolrDocument class's mime_type method returning "null" for these documents. I believe that this is because of Fedora being down, but I don't see why that should be the case. 
I am currently adding a somewhat hacky solution to display the images for now. I will revisit the issue of mime_type when Fedora is back online (working with Daniel on that in parallel)

**Comment by NedHenry** [comment]
Fixed (at least temporarily) with the following commit: c797ce0d9f13fcc08ee8a4d95b9c44826dfd3a93
