### ISSUE TITLE
Date display in metadata record

### ISSUE THREAD

**Issue by rmjaffe** [UCSCLibrary/ucsc-library-digital-collections#74]
Date Created and Date Modified are displaying differently.  Date Created is being pulled in from descriptive metadata, whereas it looks like Hyrax is supplying Date Modified.

Here's an example: http://digitalcollections.library.ucsc.edu/records/wh246s25b
Date Created: 1968-07-14
Date Modified: 08/08/2018

**Comment by NedHenry** [comment]
This deserves a little explanation:

- As I understand, the Date Modified field is not actually part of our metadata record (we have Date Created, Date Digitized, and Date Published). This is extra administrative data built in to Hyrax. It automatically updates whenever we edit the object, so it always records the last time the digital object was modified in Hyrax. This is useful, but not something we need to keep up to date with a spreadsheet (since it changes every time we make an edit of any kind). This is currently one of the fields that only displays to logged in users, so the public never sees this.

- The Date Created field still needs to be altered to display a prettier, more human readable date. While we can definitely do better than we are currently doing, if we want to really do it right we'll need to do all the work we have planned to store granular dates in Hyrax. For now, it may be better to either live with the current display or add a human readable date to the "DateCreatedFake" field to display instead. If we want to do that, I could automatically add something like "July 14, 1968" to the DateCreatedFake field for every date that is recorded as "1968-07-14". This would of course, a temporary fix until I update the software to handle dates the way we want to.

Thoughts?

**Comment by rmjaffe** [comment]
Got it.  The issue here is mostly a cosmetic one.  If it's an easy fix, it would be nice to have all the dates (those ingested as part of the descriptive metadata and those supplied by Hyrax) display in the same YYYY-MM-DD format.  Or in other words, could the Hyrax-supplied Date Modified be made to display YYYY-MM-DD vs. how it's displaying now (MM/DD/YYYY)?  If it's a pain, don't worry about it!

**Comment by NedHenry** [comment]
I think it is a bit of a pain, unfortunately, but at least it isn't visible
to the public. Let's put it off for now, but leave this issue open to
remember to deal with it later.

**Comment by NedHenry** [comment]
In the newest versions of the site, the Date Modified is not displayed in the metadata record, even to logged in users. All the displayed dates are in the same formats. Nobody has complained about this, so I'm going to assume it's fine for now and close this ticket. We want to improve how we handle dates in the future.
