### ISSUE TITLE
linked terms on public item record display result in a "no results" 

### ISSUE THREAD

**Issue by chesleyperry** [UCSCLibrary/ucsc-library-digital-collections#77]
Clicking on linked terms in the item display of DAMS records results in a "no items found" error.  HEre's an example of a series link:  http://digitalcollections.library.ucsc.edu/catalog?f%5Bseries_sim%5D%5B%5D=Illusion+for+Sale

Keyword searches do work.  Collection Title links do work.  
Subjects, dates, resource types, series links do not work.  This seems to a problem with Harry Mayo also, so it's not limited to RMB/PJ.

Thanks for looking into it!

**Comment by NedHenry** [comment]
The minimum functionality has now been achieved: the links in item records work more or less as expected. 
There are still a few problems related to this issue. Namely, on the search result page, the "filters" page shows an encoded version of the search field instead of the human readable label (e.g. "resourceType_label_tesim" instead of "Resource Type"), and the facets on the left for refining the search all split the terms into multiple words and make them all lower case (which makes problems). I'll look into these two remaining issues.

**Comment by NedHenry** [comment]
The remaining issues mentioned above were fixed some time ago. I am only now getting around to closing the issue.
