### ISSUE TITLE
Blurry Image

### ISSUE THREAD

**Issue by JessWaggs** [UCSCLibrary/ucsc-library-digital-collections#89]
Only blurry when viewed through Universal Viewer:
http://digitalcollections.library.ucsc.edu/concern/works/5425kb302?universal_viewer=true&locale=en#?c=0&m=0&s=0&cv=0&xywh=-7330%2C0%2C20403%2C10781

**Comment by NedHenry** [comment]
This is usually happens when the image has never been loaded in the Universal Viewer before, and usually the image should get clear in a few seconds after the image server generates smaller images and sends them to the viewer.
However, this morning the image server went down for some reason. I am looking into that now.
I am also noticing that I don't have alerts set up to tell me if this server goes down, since it was the last server I added. I am adding alerts for that now.

**Comment by NedHenry** [comment]
The image server is back online, and this image does indeed get clear now. This highlights that I need to make sure the image server is online 100% of the time. We added CPU resources to the this server and improved the monitoring program so we will know immediately if this happens again. Load testing the image server is getting added to the queue of work to do.
